// Publish the selected letter at /science/ while sharing its existing assets.
// Edit the source pages, then regenerate these public routes with this script.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { posix } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = new URL('../../', import.meta.url);
const origin = 'https://build.invalid';
const pages = new Map([
  ['/site/letter/studies/split-view.html', '/science/index.html'],
  ['/site/letter/check/index.html', '/science/check/index.html'],
  ['/site/letter/paper/index.html', '/science/paper/index.html'],
]);
const routes = new Map([
  ['/site/letter/', '/science/'],
  ['/site/letter/index.html', '/science/'],
  ...[...pages].flatMap(([source, target]) => {
    const route = target.replace(/index\.html$/, '');
    return [[source, route], ...(source.endsWith('/index.html') ? [[source.replace(/index\.html$/, ''), route]] : [])];
  }),
]);

for (const [source, destination] of pages) {
  const targetDirectory = posix.dirname(destination);
  const relative = value => {
    if (!value || value.startsWith('#')) return value;
    const url = new URL(value, origin + source);
    if (url.origin !== origin) return value;
    const target = routes.get(url.pathname) || url.pathname;
    if (!routes.has(url.pathname) && !existsSync(new URL('.' + target, root))) {
      throw new Error(`Missing local resource in ${source}: ${value}`);
    }
    let path = posix.relative(targetDirectory, target) || '.';
    if (target.endsWith('/') && !path.endsWith('/')) path += '/';
    return path + url.search + url.hash;
  };
  let html = readFileSync(new URL('.' + source, root), 'utf8');
  html = html.replace(/\b(href|src|srcset)="([^"]*)"/g, (attribute, name, value) => {
    if (name === 'srcset' && /[,\s]/.test(value)) throw new Error(`Review multi-image srcset in ${source}`);
    return `${name}="${relative(value)}"`;
  });
  html = html.replace('<html', '<!-- Generated by services/letter-signing/build-science.mjs. Edit the source page. -->\n<html');
  const file = new URL('.' + destination, root);
  mkdirSync(fileURLToPath(new URL('./', file)), { recursive: true });
  writeFileSync(file, html);
  console.log(`Prepared ${destination}.`);
}
